const basis = [
  'icon-shujumoni',
  'icon-tongzhiguanli',
  'icon-rizhifuwu',
  'icon-keshihua',
  'icon-yuanchengshengji',
  'icon-shebei',
  'icon-wangluozujian',
  'icon-shipinwangguan',
  'icon-wangguanzishebei',
  'icon-zhihuishequ',
  'icon-chanpinfenlei',
  'icon-zhengshuguanli',
  'icon-zhihuigongye',
  'icon-chanpin',
  'icon-changjingliandong',
  'icon-zhilianshebei',
  'icon-zidingyiguize',
  'icon-zhihuichengshi',
  'icon-chajianguanli',
  'icon-zhihuiyuanqu',
  'icon-fenpingzhanshi1',
  'icon-rili',
  'icon-renyuan',
  'icon-shezhi',
  'icon-chuli',
  'icon-anniuguanli',
  'icon-tongzhijilu',
  'icon-shuxingpeizhi',
  'icon-xiaoxi',
  'icon-guojijilian',
  'icon-quanxianguanli',
  'icon-xuanzetongdao1',
  'icon-yonghuguanli',
  'icon-bumenguanli',
  'icon-caidanguanli',
  'icon-Vector',
  'icon-Union',
  'icon-shebeigaojing',
  'icon-bianyuanwangguan',
  'icon-wuguanli',
  'icon-yunyunjieru',
  'icon-wulianwang',
  'icon-shebeiguanli',
  'icon-xitongguanli1',
  'icon-yunweiguanli-1',
  'icon-jiaoseguanli',
];

const suggestion = [
    'Question',
    'QuestionCircle',
    'Plus',
    'PlusCircle',
    'Pause',
    'PauseCircle',
    'Minus',
    'MinusCircle',
    'PlusSquare',
    'MinusSquare',
    'Info',
    'InfoCircle',
    'Exclamation',
    'ExclamationCircle',
    'Close',
    'CloseCircle',
    'CloseSquare',
    'Check',
    'CheckCircle',
    'CheckSquare',
    'ClockCircle',
    'Warning',
    'IssuesClose',
    'Stop',
];

const editor = [
    'Edit',
    'Form',
    'Copy',
    'Scissor',
    'Delete',
    'Snippets',
    'Diff',
    'Highlight',
    'AlignCenter',
    'AlignLeft',
    'AlignRight',
    'BgColors',
    'Bold',
    'Italic',
    'Underline',
    'Strikethrough',
    'Redo',
    'Undo',
    'ZoomIn',
    'ZoomOut',
    'FontColors',
    'FontSize',
    'LineHeight',
    'Dash',
    'SmallDash',
    'SortAscending',
    'SortDescending',
    'Drag',
    'OrderedList',
    'UnorderedList',
    'RadiusSetting',
    'ColumnWidth',
    'ColumnHeight',
];

const data = [
    'AreaChart',
    'PieChart',
    'BarChart',
    'DotChart',
    'LineChart',
    'RadarChart',
    'HeatMap',
    'Fall',
    'Rise',
    'Stock',
    'BoxPlot',
    'Fund',
    'Sliders',
];

const datum = [...suggestion, ...editor, ...data];

const iconKeys = datum.map((item) => item + 'Outlined');

export default [...basis, ...iconKeys];
