// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BadgeStatus: typeof import('./src/components/BadgeStatus/index.vue')['default']
    CardBox: typeof import('./src/components/CardBox/index.vue')['default']
    GeoComponent: typeof import('./src/components/GeoComponent/index.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValueItem: typeof import('./src/components/ValueItem/index.vue')['default']
  }
}
