export const columns = [
    {
        title: '车辆类型',
        dataIndex: 'vehicleTypeEnum',
        key: 'vehicleTypeEnum',
        scopedSlots: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '出厂编号',
        dataIndex: 'factoryNumber',
        key: 'factoryNumber',
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '车辆简称',
        dataIndex: 'simpleName',
        key: 'simpleName',
        search: {
            type: 'string',
        },
    },
    {
        title: '故障设备',
        dataIndex: 'alarmDeviceName',
        key: 'alarmDeviceName',
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '故障码',
        dataIndex: 'faultCode',
        key: 'faultCode',
        scopedSlots: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '故障说明',
        dataIndex: 'description',
        key: 'description',
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '型号',
        dataIndex: 'modelNumber',
        key: 'modelNumber',
        ellipsis: true,
        scopedSlots: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '所属组织',
        dataIndex: 'orgName',
        key: 'orgName',
        scopedSlots: true,
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '故障时间 ',
        dataIndex: 'faultTime',
        key: 'faultTime',
        width: 180,
        scopedSlots: true,
        search: {
            type: 'date',
        },
    },
    {
        title: '车辆位置',
        dataIndex: 'lngLat',
        key: 'lngLat',
        scopedSlots: true,
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
];

export const mockData = {
    pageIndex: 0,
    pageSize: 12,
    total: 13,
    data: [
        {
            vehicleTypeEnum: 'SUV',
            factoryNumber: 'V2023B002',
            simpleName: '途观',
            alarmDeviceName: '制动系统报警器',
            faultCode: 'C0035',
            description: '左后轮速传感器故障',
            modelNumber: 'SVW6451EED',
            faultTime: '2023-04-02T09:15:00',
            lngLat: '121.47,31.23',
        },
        {
            vehicleTypeEnum: 'MPV',
            factoryNumber: 'V2023C003',
            simpleName: '奥德赛',
            alarmDeviceName: '排放系统报警器',
            faultCode: 'P0420',
            description: '催化转换器效率低于阈值',
            modelNumber: 'HG6481BAA',
            orgName: '广汽本田汽车有限公司',
            faultTime: '2023-04-03T14:45:00',
            lngLat: '113.23,23.16',
        },
        {
            vehicleTypeEnum: '轿车',
            factoryNumber: 'V2023D004',
            simpleName: '帕萨特',
            alarmDeviceName: '点火系统报警器',
            faultCode: 'P0300',
            description: '多缸失火',
            modelNumber: 'SVW71810DJ',
            orgName: '上海大众汽车有限公司',
            faultTime: '2023-04-01T07:30:00',
            lngLat: '121.47,31.23',
        },
        {
            vehicleTypeEnum: 'SUV',
            factoryNumber: 'V2023E005',
            simpleName: '哈弗H6',
            alarmDeviceName: '冷却系统报警器',
            faultCode: 'P0128',
            description: '冷却液温度低于节温器调节温度',
            modelNumber: 'CC6461RM01',
            orgName: '长城汽车股份有限公司',
            faultTime: '2023-04-04T16:00:00',
            lngLat: '115.82,39.90',
        },
        {
            vehicleTypeEnum: '轿车',
            factoryNumber: 'V2023F006',
            simpleName: '思域',
            alarmDeviceName: '排放系统报警器',
            faultCode: 'P0430',
            description: '催化转换器系统效能低于阈值',
            modelNumber: 'DHW7182FRASD',
            orgName: '东风本田汽车有限公司',
            faultTime: '2023-04-02T11:45:00',
            lngLat: '114.31,22.54',
        },
        {
            vehicleTypeEnum: 'MPV',
            factoryNumber: 'V2023G007',
            simpleName: '瑞风',
            alarmDeviceName: '电气系统报警器',
            faultCode: 'B1000',
            description: '气囊控制模块故障',
            modelNumber: 'HFC6500A1C7S',
            orgName: '安徽江淮汽车集团股份有限公司',
            faultTime: '2023-04-05T08:15:00',
            lngLat: '117.27,31.86',
        },
        {
            vehicleTypeEnum: 'SUV',
            factoryNumber: 'V2023H008',
            simpleName: '传祺GS4',
            alarmDeviceName: '转向系统报警器',
            faultCode: 'C1234',
            description: '电动助力转向系统故障',
            modelNumber: 'GAC6461DAA1',
            orgName: '广州汽车集团乘用车有限公司',
            faultTime: '2023-04-04T13:30:00',
            lngLat: '113.23,23.16',
        },
        {
            vehicleTypeEnum: '轿车',
            factoryNumber: 'V2023I009',
            simpleName: '轩逸',
            alarmDeviceName: '燃油系统报警器',
            faultCode: 'P0172',
            description: '燃油系统过浓',
            modelNumber: 'DFL7160VBNH2',
            orgName: '东风日产乘用车公司',
            faultTime: '2023-04-01T17:45:00',
            lngLat: '114.07,22.54',
        },
        {
            vehicleTypeEnum: 'MPV',
            factoryNumber: 'V2023J010',
            simpleName: '宝骏730',
            alarmDeviceName: '传动系统报警器',
            faultCode: 'P0705',
            description: '变速器档位传感器电路故障',
            modelNumber: 'LZW6476EVF',
            orgName: '上汽通用五菱汽车股份有限公司',
            faultTime: '2023-04-03T09:00:00',
            lngLat: '109.40,24.31',
        },
        {
            vehicleTypeEnum: 'SUV',
            factoryNumber: 'V2023K011',
            simpleName: '博越',
            alarmDeviceName: '车身稳定系统报警器',
            faultCode: 'C0040',
            description: '车轮转速传感器故障',
            modelNumber: 'JL6460L01',
            orgName: '浙江吉利汽车有限公司',
            faultTime: '2023-04-05T15:15:00',
            lngLat: '121.50,30.86',
        },
        {
            vehicleTypeEnum: '轿车',
            factoryNumber: 'V2023L012',
            simpleName: '卡罗拉',
            alarmDeviceName: '点火系统报警器',
            faultCode: 'P0301',
            description: '第一缸失火',
            modelNumber: 'TV7167GL-iHE',
            orgName: '一汽丰田汽车有限公司',
            faultTime: '2023-04-02T18:30:00',
            lngLat: '116.38,39.90',
        },
        {
            vehicleTypeEnum: 'MPV',
            factoryNumber: 'V2023M013',
            simpleName: '大通G10',
            alarmDeviceName: '制动系统报警器',
            faultCode: 'C1145',
            description: 'ABS系统压力传感器故障',
            modelNumber: 'SH6521A4D4',
            orgName: '上汽大通汽车有限公司',
            faultTime: '2023-04-01T10:45:00',
            lngLat: '121.59,31.07',
        },
        {
            vehicleTypeEnum: 'SUV',
            factoryNumber: 'V2023N014',
            simpleName: '昂科威',
            alarmDeviceName: '悬挂系统报警器',
            faultCode: 'C0561',
            description: '悬挂控制系统故障',
            modelNumber: 'SGM6475DAX1',
            orgName: '上汽通用汽车有限公司',
            faultTime: '2023-04-04T11:00:00',
            lngLat: '121.43,31.22',
        },
    ],
};
