export const columns = [
    {
        title: '车辆类型',
        dataIndex: 'vehicleTypeEnum',
        key: 'vehicleTypeEnum',
        ellipsis: true,
        scopedSlots: true,
        search: {
            type: 'select',
            options: [],
        },
    },
    {
        title: '出厂编号',
        dataIndex: 'factoryNumber',
        key: 'factoryNumber',
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '车牌号',
        dataIndex: 'vehicleNumber',
        key: 'vehicleNumber',
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '车辆简称',
        dataIndex: 'simpleName',
        key: 'simpleName',
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '运行状态',
        dataIndex: 'status',
        key: 'status',
        ellipsis: true,
        scopedSlots: true,
        search: {
            type: 'select',
            options: [
                {
                    label: '在线',
                    value: 0,
                },
                {
                    label: '离线',
                    value: 1,
                },
                {
                    label: '禁用',
                    value: 2,
                },
            ],
        },
    },
    {
        title: '最高限速',
        dataIndex: 'maximumSpeedLimit',
        key: 'maximumSpeedLimit',
        ellipsis: true,
        scopedSlots: true,
    },
    {
        title: '报警速度',
        dataIndex: 'alarmSpeed',
        key: 'alarmSpeed',
        ellipsis: true,
        scopedSlots: true,
    },
    {
        title: '远程锁车',
        dataIndex: 'remoteLock',
        key: 'remoteLock',
        ellipsis: true,
        scopedSlots: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '碰撞阈值',
        dataIndex: 'collision',
        key: 'collision',
        ellipsis: true,
        scopedSlots: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '超载阈值',
        dataIndex: 'overload',
        key: 'overload',
        ellipsis: true,
        scopedSlots: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '车速校准',
        dataIndex: 'vehicleSpeed',
        key: 'vehicleSpeed',
        scopedSlots: true,
        ellipsis: true,
    },
    {
        title: '称重校准',
        dataIndex: 'weighingCalibration',
        key: 'weighingCalibration',
        scopedSlots: true,
        ellipsis: true,
    },
    {
        title: '型号',
        dataIndex: 'modelNumber',
        key: 'modelNumber',
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
    {
        title: '所属组织',
        dataIndex: 'orgName',
        key: 'orgName',
        scopedSlots: true,
        ellipsis: true,
        search: {
            type: 'string',
        },
    },
];

export const data = [
    {
        orgName: '安徽合力有限公司',
        alarmDictionaryValue: '02',
        alarmDeviceName: '锂电电动车',
        vehicleTypeEnum: 'other',
        factoryNumber: ' HL-1002548',
        deviceId: '1794984010576781312',
        vehicleNumber: '粤B-AA2349',
        status: 0,
        maximumSpeedLimit: 50,
        alarmSpeed: 60,
        remoteLock: 0,
        collision: 140,
        overload: 3,
        simpleName: '21990001',
        modelNumber: 'CT-129-2024',
        id: '1798902302436433923',
        timestamp: 1717726705546,
    },
    {
        orgName: '安徽合力有限公司',
        alarmDictionaryValue: '02',
        alarmDeviceName: '内燃汽油车',
        vehicleTypeEnum: '内燃汽油车',
        factoryNumber: ' HL-1002034',
        deviceId: '1794984010576781312',
        vehicleNumber: '渝A-2D997',
        status: 1,
        maximumSpeedLimit: 40,
        alarmSpeed: 60,
        remoteLock: 1,
        collision: 240,
        overload: 8,
        simpleName: '21990002',
        modelNumber: 'HL-2024G-07',
        id: '1798902302436433922',
        timestamp: 1717726705546,
    },
    {
        orgName: '安徽合力有限公司',
        alarmDictionaryValue: '02',
        alarmDeviceName: '锂电电动车',
        vehicleTypeEnum: 'other',
        factoryNumber: ' HL-1002129',
        deviceId: '1794984010576781312',
        vehicleNumber: '粤A-CA520',
        status: 1,
        maximumSpeedLimit: 50,
        alarmSpeed: 60,
        remoteLock: 0,
        collision: 200,
        overload: 9,
        simpleName: '21990003',
        modelNumber: 'HL-2G69-T',
        id: '1798902302436433920',
        timestamp: 1717726705546,
    },
    {
        orgName: '安徽合力有限公司',
        alarmDictionaryValue: '02',
        alarmDeviceName: '内燃汽油车',
        vehicleTypeEnum: '内燃汽油车',
        factoryNumber: ' HL-1002407',
        deviceId: '1794984010576781312',
        vehicleNumber: '渝A-AC120',
        status: 1,
        maximumSpeedLimit: 60,
        alarmSpeed: 70,
        remoteLock: 0,
        collision: 200,
        overload: 4,
        simpleName: '21990004',
        modelNumber: 'HL-2024-112',
        id: '1798902302436433921',
        timestamp: 1717726705546,
    },
];
