export const  mediaConfigMap = new Map()
mediaConfigMap.set('onvif-record','onvif-record')
mediaConfigMap.set('onvif-ptz','onvif-ptz')
mediaConfigMap.set('fixed-media-record','fix-record')
mediaConfigMap.set('fixed-media-ptz','fix-ptz')
mediaConfigMap.set('gb28181-2016-ptz','gb-ptz')
mediaConfigMap.set('gb28181-2016-record','gb-record')
mediaConfigMap.set('media-plugin-ptz','plugin-ptz')
mediaConfigMap.set('media-plugin-record','plugin-record')

