import { IDiagnoseItem } from '@/views/device/OfflineManage/typings';

export const columnsConf = [
    {
        title: 'ID',
        dataIndex: 'id',
        key: 'id',
        ellipsis: false,
        innerWidth: 300,
        search: {
            type: 'string',
        },
    },
    {
        title: '采集模型',
        dataIndex: 'productName',
        key: 'productName',
        ellipsis: true,
        search: {
            type: 'string',
        },
        scopedSlots: true,
    },
    {
        title: '设备名称',
        dataIndex: 'name',
        key: 'name',
        ellipsis: true,
        search: {
            type: 'string',
        },
        scopedSlots: true,
    },
    {
        title: '设备类型',
        dataIndex: 'deviceType',
        key: 'deviceType',
        ellipsis: true,
        search: {
            type: 'select',
            options: [
                {
                    label: '直连设备',
                    value: 'device',
                },
                {
                    label: '网关设备',
                    value: 'gateway',
                },
                {
                    label: '网关子设备',
                    value: 'childrenDevice',
                },
            ],
        },
        scopedSlots: true,
    },
    {
        title: '离线时间',
        dataIndex: 'offlineTime',
        key: 'offlineTime',
        ellipsis: true,
        scopedSlots: true,
        width: 180,
    },
    {
        title: '状态',
        dataIndex: 'state',
        key: 'state',
        width: 100,
        // search: {
        //     type: 'select',
        //     options: [
        //         { label: '在线', text: '在线', value: 'online' },
        //         { label: '离线', text: '离线', value: 'offline' },
        //         { label: '未激活', text: '未激活', value: 'notActive' },
        //     ],
        // },
        scopedSlots: true,
    },
    {
        title: '离线原因',
        dataIndex: 'offlineReasons',
        key: 'offlineReasons',
        ellipsis: true,
        search: {
            type: 'string',
        },
        scopedSlots: true,
    },
    {
        title: '操作',
        dataIndex: 'action',
        key: 'action',
        width: 100,
        // fixed: 'right',
        scopedSlots: true,
    },
];

export const mockData = {
    status: 200,
    code: 200,
    message: 'success',
    result: {
        data: [
            {
                id: '2002000481',
                photoUrl:
                    'http://47.108.154.43:9100/images/device/instance/device-card.png',
                name: '2002000481',
                deviceType: {
                    text: '直连设备',
                    value: 'device',
                },
                productId: '1794397450438037504',
                productName: '企标',
                state: {
                    text: '离线',
                    value: 'offline',
                },
                creatorId: '1199596756811550720',
                creatorName: '超级管理员',
                createTime: 1721900849098,
                registryTime: 1721900850968,
                features: [],
                modifyTime: 1721901829975,
                modifierId: '1199596756811550720',
                modifierName: '超级管理员',
            },
            {
                id: '3030000022',
                name: '3030000022',
                deviceType: {
                    text: '直连设备',
                    value: 'device',
                },
                productId: 'unknowndevice',
                productName: '企标自注册设备',
                configuration: {},
                state: {
                    text: '在线',
                    value: 'online',
                },
                creatorId: '1199596756811550720',
                createTime: 1721376675088,
                registryTime: 1721376675084,
                features: [],
                modifyTime: 1721785089606,
                modifierId: '1199596756811550720',
                modifierName: '超级管理员',
            },
            {
                id: 'L54110400R43J1739',
                name: 'L54110400R43J1739',
                deviceType: {
                    text: '直连设备',
                    value: 'device',
                },
                productId: 'national_environmental_model',
                productName: '国标',
                configuration: {},
                state: {
                    text: '离线',
                    value: 'offline',
                },
                creatorId: '1199596756811550720',
                createTime: 1721108824084,
                registryTime: 1721108824079,
                features: [],
                modifyTime: 1721120676931,
                modifierId: '1199596756811550720',
                modifierName: '超级管理员',
            },
            {
                id: 'L54110400R43J1738',
                name: 'L54110400R43J1738',
                deviceType: {
                    text: '直连设备',
                    value: 'device',
                },
                productId: 'national_environmental_model',
                productName: '国标',
                configuration: {},
                state: {
                    text: '离线',
                    value: 'offline',
                },
                creatorId: '1199596756811550720',
                createTime: 1721108821796,
                registryTime: 1721108821789,
                features: [],
                modifyTime: 1721706996471,
                modifierId: '1199596756811550720',
                modifierName: '超级管理员',
            },
            {
                id: 'L54110400R43J1737',
                name: 'L54110400R43J1737',
                deviceType: {
                    text: '直连设备',
                    value: 'device',
                },
                productId: 'national_environmental_model',
                productName: '国标',
                configuration: {},
                state: {
                    text: '离线',
                    value: 'offline',
                },
                creatorId: '1199596756811550720',
                createTime: 1721108819946,
                registryTime: 1721108819940,
                features: [],
                modifyTime: 1721706773438,
                modifierId: '1199596756811550720',
                modifierName: '超级管理员',
            },
            {
                id: 'L54110400R43J1736',
                name: 'L54110400R43J1736',
                deviceType: {
                    text: '直连设备',
                    value: 'device',
                },
                productId: 'national_environmental_model',
                productName: '国标',
                configuration: {},
                state: {
                    text: '离线',
                    value: 'offline',
                },
                creatorId: '1199596756811550720',
                createTime: 1721108817684,
                registryTime: 1721108817678,
                features: [],
                modifyTime: 1721706767410,
                modifierId: '1199596756811550720',
                modifierName: '超级管理员',
            },
        ],
    },
};
